// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgxQrzcnQvnSHXwJ0wlCdoBbDtB5sQ8I',
    appId: '1:403556640177:web:298ba41a23f5da59ca4990',
    messagingSenderId: '403556640177',
    projectId: 'eshop-d0824',
    authDomain: 'eshop-d0824.firebaseapp.com',
    storageBucket: 'eshop-d0824.appspot.com',
    measurementId: 'G-FS1GXLSDXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbHiA9txT6fOt17NqKNt7vFsrnk8hR1Y',
    appId: '1:403556640177:android:02c32b3e94903f84ca4990',
    messagingSenderId: '403556640177',
    projectId: 'eshop-d0824',
    storageBucket: 'eshop-d0824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpltSioeOv71h5W7LVi95BLeiBVEOmlvI',
    appId: '1:403556640177:ios:caaa321b135e5fcbca4990',
    messagingSenderId: '403556640177',
    projectId: 'eshop-d0824',
    storageBucket: 'eshop-d0824.appspot.com',
    iosClientId: '403556640177-mu7ir03nk4bsdqrf729spfrm28t4bisk.apps.googleusercontent.com',
    iosBundleId: 'com.example.estore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpltSioeOv71h5W7LVi95BLeiBVEOmlvI',
    appId: '1:403556640177:ios:7fb6d0537fd36f7dca4990',
    messagingSenderId: '403556640177',
    projectId: 'eshop-d0824',
    storageBucket: 'eshop-d0824.appspot.com',
    iosClientId: '403556640177-lisif6gkmj23l400m1rbdeg78evf360l.apps.googleusercontent.com',
    iosBundleId: 'com.example.estore.RunnerTests',
  );
}
